<?php

namespace CloudAtlas\Test\Unit\Credentials;

use CloudAtlas\Credentials\AbstractCredentialProvider;
use CloudAtlas\Test\Unit\AbstractTestCase;

class AbstractCredentialProviderTest extends AbstractTestCase
{
    private $key, $secret, $profile;

    private function clearEnv()
    {
        putenv(AbstractCredentialProvider::ENV_KEY . '=');
        putenv(AbstractCredentialProvider::ENV_SECRET . '=');
        putenv(AbstractCredentialProvider::ENV_PROFILE . '=');
        $dir = sys_get_temp_dir() . '/.cloudatlas';
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }
        return $dir;
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->key = getenv(AbstractCredentialProvider::ENV_KEY);
        $this->secret = getenv(AbstractCredentialProvider::ENV_SECRET);
        $this->profile = getenv(AbstractCredentialProvider::ENV_PROFILE);
    }

    public function tearDown()
    {
        parent::tearDown();
        putenv(AbstractCredentialProvider::ENV_KEY . '=' . $this->key);
        putenv(AbstractCredentialProvider::ENV_SECRET . '=' . $this->secret);
        putenv(AbstractCredentialProvider::ENV_PROFILE . '=' . $this->profile);
    }

    public function testCreatesFromEnvironmentVariables()
    {
        $this->clearEnv();
        putenv(AbstractCredentialProvider::ENV_KEY . '=abc');
        putenv(AbstractCredentialProvider::ENV_SECRET . '=123');
        $credential = AbstractCredentialProvider::env()->wait();
        $this->assertEquals('abc', $credential->getKey());

    }
}

